[package]
name = "volume-control-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulsectl-rs = "0.3.2"
notify-rust = "4.6.0"
clap = { version = "4.0.29", features = ["derive"] }
